version: '2.1'

services:
  web:
    container_name: ojs-web
    build: .
    ports:
      - '3022:80'
    env_file: .env
    environment:
      OJS_DB_HOST: 'mysql'
      OJS_DB_USER: 'root'
      OJS_DB_PASSWORD: ''
      OJS_DB_NAME: 'ojs'
      BASE_URL: 'www.test.com'
      OJS_INSTALLED: 'Off'
      OJS_SALT: 'abc'
      SERVERNAME: 'test.com'
    links:
      - mysql
  mysql:
    container_name: ojs-mysql
    image: mysql:5.6
    ports:
      - "0.0.0.0:3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "ojs"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
